#! /bin/bash
#for CPUFREQ in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do [ -f $CPUFREQ ] || continue; echo -n performance > $CPUFREQ; done

#for CPUFREQ in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do [ -f $CPUFREQ ] || continue; cat $CPUFREQ; done

#grep -E '^model name|^cpu MHz' /proc/cpuinfo

sudo cpupower frequency-set --governor performance
sudo sh -c 'echo -1 >/proc/sys/kernel/perf_event_paranoid'
sudo sh -c 'echo 0 >/proc/sys/kernel/yama/ptrace_scope'
sudo sh -c 'echo 0 >/proc/sys/kernel/kptr_restrict'
cpufreq-info
