InlayHints:
  Designators: Yes
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
Diagnostics:
  UnusedIncludes: Strict
CompileFlags:
  Add: 
  Remove:
    - "-Xcompiler=*"
    - -G
    - --expt-relaxed-constexpr


